# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
<<<<<<< HEAD
CMAKE_COMMAND = /gpfs/shareapps/apps/modulessoftware/cmake/2.8.7/bin/cmake

# The command to remove a file.
RM = /gpfs/shareapps/apps/modulessoftware/cmake/2.8.7/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/imrefran/tma4280/ex6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/imrefran/tma4280/ex6
=======
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/didrik/git/TMA4280/ex6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/didrik/git/TMA4280/ex6
>>>>>>> 6672f02924a43e4e1df8bf268517ea658bb6271d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
<<<<<<< HEAD
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
=======
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
>>>>>>> 6672f02924a43e4e1df8bf268517ea658bb6271d
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
<<<<<<< HEAD
	/gpfs/shareapps/apps/modulessoftware/cmake/2.8.7/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
=======
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
>>>>>>> 6672f02924a43e4e1df8bf268517ea658bb6271d
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
<<<<<<< HEAD
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imrefran/tma4280/ex6/CMakeFiles /home/imrefran/tma4280/ex6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imrefran/tma4280/ex6/CMakeFiles 0
=======
	$(CMAKE_COMMAND) -E cmake_progress_start /home/didrik/git/TMA4280/ex6/CMakeFiles /home/didrik/git/TMA4280/ex6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/didrik/git/TMA4280/ex6/CMakeFiles 0
>>>>>>> 6672f02924a43e4e1df8bf268517ea658bb6271d
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named poisson

# Build rule for target.
poisson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poisson
.PHONY : poisson

# fast build rule for target.
poisson/fast:
	$(MAKE) -f CMakeFiles/poisson.dir/build.make CMakeFiles/poisson.dir/build
.PHONY : poisson/fast

#=============================================================================
# Target rules for targets named poisson-f

# Build rule for target.
poisson-f: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poisson-f
.PHONY : poisson-f

# fast build rule for target.
poisson-f/fast:
	$(MAKE) -f CMakeFiles/poisson-f.dir/build.make CMakeFiles/poisson-f.dir/build
.PHONY : poisson-f/fast

fst.o: fst.f.o
.PHONY : fst.o

# target to build an object file
fst.f.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/fst.f.o
.PHONY : fst.f.o

poisson.o: poisson.c.o
.PHONY : poisson.o

# target to build an object file
poisson.c.o:
	$(MAKE) -f CMakeFiles/poisson.dir/build.make CMakeFiles/poisson.dir/poisson.c.o
.PHONY : poisson.c.o

poisson.i: poisson.c.i
.PHONY : poisson.i

# target to preprocess a source file
poisson.c.i:
	$(MAKE) -f CMakeFiles/poisson.dir/build.make CMakeFiles/poisson.dir/poisson.c.i
.PHONY : poisson.c.i

poisson.s: poisson.c.s
.PHONY : poisson.s

# target to generate assembly for a file
poisson.c.s:
	$(MAKE) -f CMakeFiles/poisson.dir/build.make CMakeFiles/poisson.dir/poisson.c.s
.PHONY : poisson.c.s

poisson.o: poisson.f.o
.PHONY : poisson.o

# target to build an object file
poisson.f.o:
	$(MAKE) -f CMakeFiles/poisson-f.dir/build.make CMakeFiles/poisson-f.dir/poisson.f.o
.PHONY : poisson.f.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... common"
	@echo "... edit_cache"
	@echo "... poisson"
	@echo "... poisson-f"
	@echo "... rebuild_cache"
	@echo "... fst.o"
	@echo "... poisson.o"
	@echo "... poisson.i"
	@echo "... poisson.s"
	@echo "... poisson.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

